services:
  web:
    build:
      context: .
      target: development
    ports:
      - "4567:4567"
      - "9394:9394"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - env.development
      - .env
        
  circulation-history:
    image: ghcr.io/mlibrary/circulation_history_unstable:latest
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - MARIADB_ROOT_PASSWORD=pass
      - CIRCULATION_HISTORY_DATABASE_PASSWORD=circulation_history_db_password
      - DATABASE_HOST=circulation-history-db
      - SECRET_KEY_BASE=secret_key_base
    env_file:
      - .env

  circulation-history-db:
    image: ghcr.io/mlibrary/circulation_history_dev_db:latest

  sass:
    build:
      context: .
      target: development
    volumes:
      - ./css:/app/css
      - ./public/bundles:/app/public/bundles
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    command: "npm run watch-css"

  esbuild:
    build:
      context: .
      target: development
    volumes:
      - ./js:/app/js
      - ./public/bundles:/app/public/bundles
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./eslint.config.mjs:/app/eslint.config.mjs
    command: "npm run watch-js"

volumes:
  gem_cache:
  circ_history_db:
