source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'sinatra'
gem 'httparty'

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'rack-test'
  gem 'rspec'
  gem 'sinatra-contrib'
  gem 'webmock'
end

