name: Run CI

on:
  push:
    branches:
      - $default-branch

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          git submodule update --init metslib
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run web
