name: Dependabot pull requests

on:
  workflow_run:
    # Make sure `test.yml` successfully completes
    workflows: ["Run Tests"]
    types:
      - completed
  pull_request:

jobs:
  dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.user.login == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PR_URL: ${{github.event.pull_request.html_url}}
    steps:
      - name: Fetch Dependabot Metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
      # Prevent merging for testing
      # - name: Merge the PR
      #   run: gh pr merge --squash --auto "$PR_URL"
