name: Dependabot pull requests

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    # Only trigger if tests have passed on a Dependabot-created PR
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests != '' &&
      startsWith(github.event.workflow_run.head_branch, 'dependabot/') &&
      github.event.workflow_run.pull_requests[0].user.login == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
    steps:
      - name: Fetch Dependabot Metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
      - name: Merge the PR
        run: gh pr merge --squash --auto "$PR_URL"
