name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

jobs:
  build-production:
    name: Build production ${{ github.event.inputs.tag }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-production:
    needs: build-production
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to Production
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}
